name: o3-log on release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  append-o3-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare entry
        id: prep
        run: |
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TAG="${{ github.event.release.tag_name || github.ref_name }}"
          ACTOR="${{ github.actor }}"
          REPO="${{ github.repository }}"
          URL="${{ github.event.release.html_url || format('https://github.com/{0}/releases', github.repository) }}"
          {
            echo ""
            echo "---"
            echo "## Entry — ${TS} (release)"
            echo "- Event: Release published"
            echo "- Actor: ${ACTOR}"
            echo "- Tag: ${TAG}"
            echo "- Link: ${URL}"
            echo "- Notes: Semantic checkpoint for auditability."
          } >> docs/o3-monitoring.md

          # JSON line
          mkdir -p docs
          echo "{\"ts\":\"${TS}\",\"event\":\"release\",\"actor\":\"${ACTOR}\",\"tag\":\"${TAG}\",\"repo\":\"${REPO}\",\"url\":\"${URL}\"}" >> docs/o3-monitoring.jsonl

      - name: Commit and push
        run: |
          git config user.name "o3-monitor"
          git config user.email "actions@users.noreply.github.com"
          git add docs/o3-monitoring.md docs/o3-monitoring.jsonl
          if ! git diff --cached --quiet; then
            git commit -m "o3-log: append release entry for ${{ github.event.release.tag_name || github.ref_name }}"
            git push
          else
            echo "No changes to commit."
          fi
